# Generated by Django 3.2.3 on 2021-07-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='head',
            name='description',
            field=models.CharField(max_length=250),
        ),
    ]
