# Generated by Django 3.2.3 on 2021-07-06 11:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('post', models.CharField(max_length=15)),
                ('image', models.ImageField(default='', upload_to='media/Home/Team')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
