# Generated by Django 3.2.3 on 2021-07-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='head',
            name='facebook_account_link',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='head',
            name='instagram_account_link',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='head',
            name='linkedin_account_link',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
